# Generated by Django 6.0.7 on 2026-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'encodage")),
            ],
            options={
                'verbose_name': 'Point Géographique',
                'verbose_name_plural': 'Points Géographiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
