# Generated by Django 6.0.7 on 2026-07-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport', models.TextField(verbose_name="Rapport d'activité")),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('nombre_beneficiaires', models.PositiveIntegerField(default=0, verbose_name='Nombre de bénéficiaires')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'activité")),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CoucheGeometrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la couche')),
                ('type_geometrie', models.CharField(choices=[('point', 'Points'), ('ligne', 'Lignes'), ('polygone', 'Polygones')], max_length=20, verbose_name='Type de géométrie')),
                ('fichier_source', models.CharField(blank=True, max_length=255, verbose_name='Fichier source')),
                ('style_couleur', models.CharField(default='#3388ff', max_length=7, verbose_name='Couleur de style')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
            ],
            options={
                'verbose_name': 'Couche de géométrie',
                'verbose_name_plural': 'Couches de géométries',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('but', models.TextField(blank=True, verbose_name="But de l'activité")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Geometrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Type GeoJSON')),
                ('coordonnees', models.JSONField(verbose_name='Coordonnées')),
                ('proprietes', models.JSONField(blank=True, default=dict, verbose_name='Propriétés')),
                ('couche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='cartographie.couchegeometrie', verbose_name='Couche')),
            ],
            options={
                'verbose_name': 'Géométrie',
                'verbose_name_plural': 'Géométries',
            },
        ),
        migrations.CreateModel(
            name='PhotoActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_activites/', verbose_name='Photo')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cartographie.activite', verbose_name='Activité')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['date_upload'],
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='cartographie.projet', verbose_name='Projet'),
        ),
    ]
