# Generated by Django 6.0.7 on 2026-07-20 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0002_activite_couchegeometrie_projet_geometrie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='activite',
            name='niveau_securite',
            field=models.CharField(blank=True, max_length=20, verbose_name='Niveau de sécurité de la zone'),
        ),
        migrations.AddField(
            model_name='activite',
            name='zone_visitee',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zone visitée'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='fichier_kml',
            field=models.FileField(blank=True, upload_to='kml_imports/', verbose_name='Fichier KML généré'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_lieux/', verbose_name='Photo du lieu'),
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'itinéraire")),
                ('coordonnees', models.JSONField(verbose_name='Coordonnées du tracé')),
                ('analyse', models.JSONField(blank=True, default=list, verbose_name='Analyse des zones traversées')),
                ('alerte', models.TextField(blank=True, verbose_name='Alerte')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300, verbose_name='Action réalisée')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProfilAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction dans le projet')),
                ('motif_mission', models.TextField(blank=True, verbose_name='Motif de la mission')),
                ('photo', models.ImageField(blank=True, upload_to='agents/', verbose_name="Photo d'identité")),
                ('est_bloque', models.BooleanField(default=False, verbose_name='Bloqué')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Agent',
                'verbose_name_plural': 'Profils Agents',
            },
        ),
        migrations.CreateModel(
            name='ZoneSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la zone')),
                ('statut', models.CharField(choices=[('dangereuse', 'Zone dangereuse'), ('securisee', 'Zone sécurisée'), ('indisponible', 'Information indisponible')], max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif de déclaration')),
                ('type_geometrie', models.CharField(default='Point', max_length=50, verbose_name='Type de géométrie')),
                ('coordonnees', models.JSONField(help_text='Coordonnées GeoJSON', verbose_name='Coordonnées')),
                ('rayon', models.FloatField(default=0, help_text='Rayon en mètres pour les zones ponctuelles', verbose_name='Rayon (m)')),
                ('date_declaration', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_crees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Zone de sécurité',
                'verbose_name_plural': 'Zones de sécurité',
                'ordering': ['-date_declaration'],
            },
        ),
    ]
