# Generated by Django 6.0.7 on 2026-07-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0004_initial_admin_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilagent',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='profilagent',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
