# Generated by Django 6.0.7 on 2026-07-31 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0005_profilagent_latitude_profilagent_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointgeographique',
            name='categorie',
            field=models.CharField(choices=[('hopital', 'Hôpital'), ('ecole', 'École'), ('eglise', 'Église'), ('police', 'Police'), ('marche', 'Marché'), ('projet', 'Projet'), ('incident', 'Incident'), ('village', 'Village'), ('ville', 'Ville'), ('pont', 'Pont'), ('route', 'Route'), ('entreprise', 'Entreprise'), ('zone_rouge', 'Zone rouge'), ('zone_verte', 'Zone verte'), ('zone_orange', 'Zone orange'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='actif', max_length=20, verbose_name='État'),
        ),
        migrations.CreateModel(
            name='MediaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo'), ('pdf', 'Document PDF'), ('audio', 'Audio')], default='photo', max_length=10, verbose_name='Type')),
                ('fichier', models.FileField(upload_to='medias_points/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='cartographie.pointgeographique', verbose_name='Point')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['date_upload'],
            },
        ),
    ]
