# Generated by Django 6.0.7 on 2026-07-31 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0006_pointgeographique_categorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='activite',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='activite',
            name='description',
            field=models.TextField(blank=True, verbose_name="Description de l'activité"),
        ),
        migrations.AddField(
            model_name='activite',
            name='nom_activite',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom de l'activité réalisée"),
        ),
        migrations.AddField(
            model_name='activite',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches', to='cartographie.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itineraires', to='cartographie.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='cartographie.activite', verbose_name='Activité'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='cartographie.projet', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='zonesecurite',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='cartographie.projet', verbose_name='Projet'),
        ),
        migrations.CreateModel(
            name='ActiviteModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'activité modèle")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_modeles', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_modeles', to='cartographie.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Activité modèle',
                'verbose_name_plural': 'Activités modèles',
                'ordering': ['nom'],
            },
        ),
    ]
