# Generated by Django 6.0.7 on 2026-08-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0008_creer_projet_pip'),
    ]

    operations = [
        migrations.AddField(
            model_name='couchegeometrie',
            name='srid',
            field=models.IntegerField(default=4326, help_text='Système de coordonnées (EPSG)', verbose_name='SRID'),
        ),
    ]
