# Generated by Django 6.0.7 on 2026-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0009_couchegeometrie_srid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointgeographique',
            name='donnees',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données complètes (import)'),
        ),
    ]
