# Generated by Django 6.0.7 on 2026-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0010_pointgeographique_donnees'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointgeographique',
            name='source_fichier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fichier source'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='source_format',
            field=models.CharField(blank=True, max_length=20, verbose_name='Format source'),
        ),
    ]
