# Generated by Django 6.0.7 on 2026-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0011_pointgeographique_source_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couchegeometrie',
            name='style_options',
            field=models.JSONField(blank=True, default=dict, help_text='Couleur, symbole, taille, opacité, étiquette et catégorisation', verbose_name='Options de style'),
        ),
    ]
