# Generated by Django 6.0.7 — Mode Avancé : codes d'accès + préférences utilisateur
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0012_couchegeometrie_style_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAccesAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, verbose_name='Libellé')),
                ('code_hash', models.CharField(max_length=64, verbose_name='Code (empreinte SHA-256)')),
                ('type', models.CharField(choices=[('temporaire', 'Code temporaire'), ('permanent', 'Code permanent')], default='permanent', max_length=20, verbose_name='Type')),
                ('expire_le', models.DateTimeField(blank=True, null=True, verbose_name="Valable jusqu'au")),
                ('max_utilisations', models.PositiveIntegerField(blank=True, help_text='Vide = illimité', null=True, verbose_name="Nombre d'utilisations max")),
                ('utilisations', models.PositiveIntegerField(default=0, verbose_name='Utilisations effectuées')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_crees', to='auth.user', verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Code d'accès au Mode Avancé",
                'verbose_name_plural': "Codes d'accès au Mode Avancé",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('classique', 'Classique'), ('avance', 'Avancé')], default='classique', max_length=20, verbose_name="Mode d'utilisation")),
                ('profil_metier', models.CharField(blank=True, max_length=30, verbose_name='Profil métier')),
                ('basemap_defaut', models.CharField(blank=True, max_length=100, verbose_name='Fond de carte par défaut')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('code_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_lies', to='cartographie.codeaccesavance', verbose_name='Code permanent utilisé')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='auth.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateurs',
            },
        ),
    ]