# Generated by Django 6.0.7 on 2026-08-04 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0013_mode_avance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FondCartePersonnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('type_fond', models.CharField(choices=[('xyz', 'XYZ / tuiles'), ('wms', 'WMS'), ('wmts', 'WMTS')], default='xyz', max_length=8, verbose_name='Type')),
                ('url', models.TextField(help_text="Modèle d'URL : {z}/{x}/{y} (XYZ), {bbox-epsg-3857} (WMS), ou {TileMatrix}/{TileCol}/{TileRow} (WMTS)", verbose_name='URL des tuiles')),
                ('attribution', models.CharField(blank=True, max_length=255, verbose_name='Attribution')),
                ('categorie', models.CharField(choices=[('geologie', 'Géologie'), ('mines', 'Mines'), ('environnement', 'Environnement'), ('topographie', 'Topographie'), ('imagerie', 'Imagerie'), ('generale', 'Cartographie générale')], default='geologie', max_length=30, verbose_name='Catégorie')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_cartes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Fond de carte personnalisé',
                'verbose_name_plural': 'Fonds de carte personnalisés',
                'ordering': ['-visible', 'ordre', 'nom'],
            },
        ),
    ]
