# Generated by Django 6.0.7 on 2026-08-04 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0014_fondcartepersonnalise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('fichier', models.ImageField(upload_to='imagerie/', verbose_name='Image')),
                ('type_imagerie', models.CharField(choices=[('ortho', 'Orthophoto'), ('drone', 'Image drone'), ('satellite', 'Imagerie satellite'), ('photo', 'Photo géolocalisée')], default='ortho', max_length=20, verbose_name="Type d'imagerie")),
                ('mode_geo', models.CharField(choices=[('worldfile', 'WorldFile'), ('exif', 'Coordonnées EXIF GPS'), ('bbox', 'Emprise manuelle')], default='bbox', max_length=20, verbose_name='Mode de géoréférencement')),
                ('min_lon', models.FloatField(blank=True, null=True, verbose_name='Longitude min (ouest)')),
                ('min_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude min (sud)')),
                ('max_lon', models.FloatField(blank=True, null=True, verbose_name='Longitude max (est)')),
                ('max_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude max (nord)')),
                ('coords', models.JSONField(blank=True, help_text='[[lon,lat] ×4] SW, SE, NE, NW — issu du WorldFile', null=True, verbose_name="Coins exacts de l'image")),
                ('altitude_m', models.FloatField(blank=True, null=True, verbose_name='Altitude de vol (m)')),
                ('date_prise', models.DateField(blank=True, null=True, verbose_name='Date de prise de vue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('visibilite', models.BooleanField(default=True, verbose_name='Visible sur la carte')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_aeriennes', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_aeriennes', to='cartographie.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Image aérienne',
                'verbose_name_plural': 'Images aériennes (orthophotos)',
                'ordering': ['-cree_le'],
            },
        ),
    ]
