# Generated by Django 6.0.7 on 2026-08-05 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0015_imageaerienne'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoucheWMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('url', models.TextField(help_text='Ex. https://serveur/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=nom&STYLES=&SRS=EPSG:3857&BBOX={bbox-epsg-3857}&WIDTH=256&HEIGHT=256&FORMAT=image/png', verbose_name='URL WMS (GetMap)')),
                ('layers', models.CharField(blank=True, max_length=500, verbose_name='Noms de couches (séparés par des virgules)')),
                ('version', models.CharField(default='1.1.1', max_length=20, verbose_name='Version WMS')),
                ('attribution', models.CharField(blank=True, max_length=255, verbose_name='Attribution')),
                ('opacite', models.FloatField(default=0.7, verbose_name='Opacité (0-1)')),
                ('visibilite', models.BooleanField(default=True, verbose_name='Visible sur la carte')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_wms', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_wms', to='cartographie.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Couche WMS',
                'verbose_name_plural': 'Couches WMS',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
