# Generated by Django 6.0.7 on 2026-08-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0016_couchewms'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondcartepersonnalise',
            name='cle_api',
            field=models.CharField(blank=True, help_text="Placez {cle_api} dans l'URL : la clé est injectée à l'affichage.", max_length=200, verbose_name='Clé API (optionnelle)'),
        ),
        migrations.AddField(
            model_name='fondcartepersonnalise',
            name='crs',
            field=models.CharField(default='EPSG:3857', help_text="MapLibre n'affiche que le Web Mercator (EPSG:3857) — autre CRS = fond documenté uniquement.", max_length=30, verbose_name='Projection / CRS'),
        ),
        migrations.AddField(
            model_name='fondcartepersonnalise',
            name='layers',
            field=models.CharField(blank=True, help_text='Nom de la couche du tuilage vectoriel à afficher (optionnel hors MVT).', max_length=300, verbose_name='Source-layer (MVT)'),
        ),
        migrations.AddField(
            model_name='fondcartepersonnalise',
            name='projet',
            field=models.ForeignKey(blank=True, help_text="Si défini, le fond est partagé dans le projet ; sinon il reste dans les préférences de l'utilisateur.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonds_cartes', to='cartographie.projet', verbose_name='Projet (portée)'),
        ),
        migrations.AlterField(
            model_name='fondcartepersonnalise',
            name='type_fond',
            field=models.CharField(choices=[('xyz', 'XYZ / tuiles raster'), ('wms', 'WMS'), ('wmts', 'WMTS'), ('vector', 'Vectoriel (MVT)'), ('geotiff', 'GeoTIFF (COG)'), ('mbtiles', 'MBTiles'), ('arcgis', 'ArcGIS REST (tuiles)')], default='xyz', max_length=8, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fondcartepersonnalise',
            name='url',
            field=models.TextField(help_text="Modèle d'URL : {z}/{x}/{y} (XYZ/MVT), {bbox-epsg-3857} (WMS), ou {TileMatrix}/{TileCol}/{TileRow} (WMTS)", verbose_name='URL des tuiles'),
        ),
    ]
