# Generated by Django 6.0.7 on 2026-08-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0017_fondcartepersonnalise_cle_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointgeographique',
            name='supprime',
            field=models.BooleanField(default=False, verbose_name='Supprimé (corbeille)'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='synchro_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Identifiant de synchronisation (client)'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Dernière modification'),
        ),
    ]
