# Generated by Django 6.0.7 on 2026-08-07 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0018_pointgeographique_supprime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetAdduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('commanditaire', models.CharField(blank=True, max_length=250, verbose_name='Commanditaire / organisme')),
                ('zone_nom', models.CharField(blank=True, help_text="Ex : secteur Irumu, territoire d'Irumu (province de l'Ituri)", max_length=250, verbose_name="Zone d'intervention")),
                ('bbox', models.JSONField(blank=True, default=list, help_text='[lon_min, lat_min, lon_max, lat_max]', verbose_name='Étendue (bbox)')),
                ('statut', models.CharField(choices=[('planifie', 'Préparation'), ('terrain', 'Collecte terrain'), ('analyse', 'Analyse & planification'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations générales')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adductions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Projet d'adduction d'eau",
                'verbose_name_plural': "Projets d'adduction d'eau",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OuvrageHydraulique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('source', "Source d'eau"), ('captage', 'Captage'), ('borne', 'Borne-fontaine'), ('consommation', 'Point de consommation'), ('reservoir', 'Réservoir'), ('ouvrage', 'Ouvrage existant'), ('repere', 'Point de repère'), ('intermediaire', 'Point intermédiaire'), ('village', 'Village desservi')], default='source', max_length=20, verbose_name="Type d'ouvrage")),
                ('nom', models.CharField(max_length=250, verbose_name='Nom / localisation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude_m', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('beneficiaires', models.PositiveIntegerField(default=0, verbose_name='Nombre de bénéficiaires')),
                ('caracteristiques', models.JSONField(blank=True, default=dict, help_text='Débit (l/s), profondeur, matériau, nombre de BF, etc.', verbose_name='Caractéristiques techniques')),
                ('observations', models.TextField(blank=True, verbose_name='Observations de terrain')),
                ('photo', models.ImageField(blank=True, upload_to='adduction/ouvrages/', verbose_name='Photo')),
                ('statut', models.CharField(choices=[('actif', 'En service'), ('moyen', 'État moyen'), ('defectueux', 'Défectueux'), ('hors_service', 'Hors service'), ('projet', 'À construire')], default='projet', max_length=20, verbose_name='État')),
                ('date_releve', models.DateTimeField(auto_now_add=True, verbose_name='Date du relevé')),
                ('releve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages_odduites', to=settings.AUTH_USER_MODEL, verbose_name='Relevé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvrages', to='cartographie.projetadduction', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Ouvrage hydraulique',
                'verbose_name_plural': 'Ouvrages hydrauliques',
                'ordering': ['date_releve'],
            },
        ),
        migrations.CreateModel(
            name='TraceAdduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, verbose_name='Nom du tracé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('coordonnees', models.JSONField(help_text='[[lon, lat, altitude], ...] évolution', verbose_name='Coordonnées du tracé')),
                ('longueur_m', models.FloatField(default=0, verbose_name='Longueur (m)')),
                ('denivelee_m', models.FloatField(default=0, verbose_name='Dénivelé cumulé positif (m)')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracs', to='cartographie.projetadduction', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Tracé de conduite',
                'verbose_name_plural': 'Tracés de conduites',
                'ordering': ['-date_creation'],
            },
        ),
    ]
