# Generated by Django 6.0.7 on 2026-08-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0019_projetadduction_ouvragehydraulique_traceadduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='agent_enqueteur',
            field=models.CharField(blank=True, max_length=150, verbose_name='Agent enquêteur'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='ID unique'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='code_projet',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code du projet'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='localite',
            field=models.CharField(blank=True, max_length=150, verbose_name='Localité'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='organisation',
            field=models.CharField(blank=True, max_length=150, verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='provenance',
            field=models.CharField(blank=True, max_length=150, verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='qualites_eau',
            field=models.JSONField(blank=True, default=dict, help_text='pH, turbidité, conductivité, chlore résiduel… — résultats non certifiants', verbose_name="Qualité de l'eau (terrain / laboratoire)"),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='secteur_chefferie',
            field=models.CharField(blank=True, max_length=150, verbose_name='Secteur / Chefferie'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='sous_type',
            field=models.CharField(blank=True, choices=[('naturelle', 'Source naturelle'), ('amenagee', 'Source aménagée'), ('forage', 'Forage'), ('puits', 'Puits'), ('riviere', 'Rivière'), ('lac', 'Lac'), ('etang', 'Étang'), ('captage_source', 'Captage'), ('gravitaire', 'Source gravitaire'), ('resurgence', 'Source à résurgence'), ('autre', 'Autre')], default='', help_text="Qualifie le type d'ouvrage (ex : pour source → naturelle, forage, puits…)", max_length=30, verbose_name='Classification / sous-type'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='territoire',
            field=models.CharField(blank=True, max_length=150, verbose_name='Territoire'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='village',
            field=models.CharField(blank=True, max_length=150, verbose_name='Village'),
        ),
        migrations.CreateModel(
            name='ReleveSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_mesure', models.FloatField(blank=True, null=True, verbose_name='Débit mesuré')),
                ('debit_unite', models.CharField(choices=[('l_s', 'L/s'), ('l_min', 'L/min'), ('m3_h', 'm³/h'), ('m3_j', 'm³/j')], default='l_s', max_length=10, verbose_name='Unité du débit')),
                ('methode_mesure', models.CharField(blank=True, choices=[('volumetrique', 'Volumétrique (récipient chronométré)'), ('deversoir', 'Déversoir / bac'), ('estime', 'Estimation'), ('pompe_jauge', 'Jaugeage de pompe'), ('autre_methode', 'Autre')], default='', max_length=30, verbose_name='Méthode de mesure')),
                ('niveau_eau_m', models.FloatField(blank=True, null=True, verbose_name="Niveau d'eau (m)")),
                ('profondeur_m', models.FloatField(blank=True, null=True, verbose_name='Profondeur (m)')),
                ('debit_saison_seche', models.FloatField(blank=True, null=True, verbose_name='Débit saison sèche')),
                ('debit_saison_pluies', models.FloatField(blank=True, null=True, verbose_name='Débit saison des pluies')),
                ('accessibilite', models.CharField(blank=True, choices=[('facile', 'Facile'), ('difficile', 'Difficile'), ('tre_difficile', 'Très difficile'), ('impossible', 'Inaccessible')], default='', max_length=20, verbose_name='Accessibilité')),
                ('etat_source', models.CharField(blank=True, choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('hors', 'Hors service')], default='', max_length=10, verbose_name='État de la source')),
                ('permanence', models.CharField(blank=True, choices=[('permanente', 'Permanente'), ('saisonniere', 'Saisonnière')], default='', max_length=12, verbose_name='Permanente / saisonnière')),
                ('protection', models.CharField(blank=True, choices=[('protegee', 'Protégée'), ('non_protegee', 'Non protégée')], default='', max_length=15, verbose_name='Protégée / non protégée')),
                ('distance_village_m', models.FloatField(blank=True, null=True, verbose_name="Distance jusqu'au village (m)")),
                ('distance_consommation_m', models.FloatField(blank=True, null=True, verbose_name='Distance au 1er point de consommation (m)')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='pH')),
                ('turbidite_ntu', models.FloatField(blank=True, null=True, verbose_name='Turbidité (NTU)')),
                ('conductivite_us', models.FloatField(blank=True, null=True, verbose_name='Conductivité (µS/cm)')),
                ('temperature_c', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('chlore_residuel', models.FloatField(blank=True, null=True, verbose_name='Chlore résiduel (mg/L)')),
                ('resultats_microbiologiques', models.TextField(blank=True, verbose_name='Résultats microbiologiques')),
                ('observation_qualite', models.TextField(blank=True, verbose_name='Observation sur la qualité')),
                ('date_prelevement', models.DateField(blank=True, null=True, verbose_name='Date du prélèvement')),
                ('code_echantillon', models.CharField(blank=True, max_length=100, verbose_name="Code de l'échantillon")),
                ('ouvrage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='releve_source', to='cartographie.ouvragehydraulique', verbose_name='Ouvrage')),
            ],
            options={
                'verbose_name': "Relevé spécialisé — Source d'eau",
                'verbose_name_plural': "Relevés spécialisés — Sources d'eau",
            },
        ),
    ]
