# Generated by Django 6.0.7 on 2026-08-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0020_ouvragehydraulique_agent_enqueteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='geometrie',
            field=models.JSONField(blank=True, default=list, help_text='[[lon, lat], …] contours fermés du village ou de la zone', verbose_name='Géométrie (polygone / zone)'),
        ),
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='representation',
            field=models.CharField(choices=[('point', 'Point'), ('polygone', 'Polygone'), ('zone', "Zone d'intervention")], default='point', help_text="Village : point, polygone ou zone d'intervention", max_length=15, verbose_name='Représentation'),
        ),
        migrations.CreateModel(
            name='ReleveVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='Population')),
                ('menages', models.PositiveIntegerField(default=0, verbose_name='Nombre de ménages')),
                ('population_cible', models.PositiveIntegerField(default=0, verbose_name='Population cible')),
                ('beneficiaires_estimes', models.PositiveIntegerField(default=0, verbose_name='Bénéficiaires estimés')),
                ('ecoles', models.PositiveIntegerField(default=0, verbose_name="Nombre d'écoles")),
                ('centres_sante', models.PositiveIntegerField(default=0, verbose_name='Nombre de centres de santé')),
                ('autres_institutions', models.TextField(blank=True, verbose_name='Autres institutions')),
                ('source_eau_actuelle', models.CharField(blank=True, choices=[('borne_publique', 'Borne-fontaine publique'), ('source_traditionnelle', 'Source / rivière traditionnelle'), ('puits', 'Puits'), ('forage', 'Forage'), ('robinet_domicile', 'Robinets à domicile'), ('livraison', 'Livraison par citerne'), ('aucun', 'Aucun accès'), ('autre_acces', 'Autre')], default='', max_length=30, verbose_name="Source d'eau actuelle")),
                ('distance_source_m', models.FloatField(blank=True, null=True, verbose_name='Distance à la source (m)')),
                ('situation_acces', models.CharField(blank=True, choices=[('adequate', 'Adéquate'), ('partielle', 'Partielle'), ('insuffisante', 'Insuffisante'), ('absente', 'Absente')], default='', max_length=15, verbose_name="Situation de l'accès à l'eau")),
                ('ouvrage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='releve_village', to='cartographie.ouvragehydraulique', verbose_name='Ouvrage')),
            ],
            options={
                'verbose_name': 'Relevé spécialisé — Village / Localité',
                'verbose_name_plural': 'Relevés spécialisés — Villages / Localités',
            },
        ),
    ]
