# Generated by Django 6.0.7 on 2026-08-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0021_ouvragehydraulique_geometrie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_desservie', models.PositiveIntegerField(default=0, verbose_name='Population desservie')),
                ('menages_desservis', models.PositiveIntegerField(default=0, verbose_name='Nombre de ménages desservis')),
                ('nombre_robinets', models.PositiveIntegerField(default=0, verbose_name='Nombre de robinets')),
                ('etat', models.CharField(blank=True, choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('hors_service', 'Hors service')], default='', max_length=20, verbose_name='État')),
                ('existant_propose', models.CharField(blank=True, choices=[('existant', 'Existant'), ('propose', 'Proposé')], default='', max_length=10, verbose_name='Existant / proposé')),
                ('debit_estime', models.FloatField(blank=True, null=True, verbose_name='Débit estimé (l/s)')),
                ('besoin_estime', models.FloatField(blank=True, null=True, verbose_name='Besoin estimé (m³/j)')),
                ('photos', models.JSONField(blank=True, default=list, help_text="Liste d'images (URL ou données base64) prises sur site", verbose_name='Photos de terrain')),
                ('ouvrage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='releve_consommation', to='cartographie.ouvragehydraulique', verbose_name='Ouvrage')),
            ],
            options={
                'verbose_name': 'Relevé spécialisé — Point de consommation',
                'verbose_name_plural': 'Relevés spécialisés — Points de consommation',
            },
        ),
        migrations.CreateModel(
            name='ReleveRepere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.TextField(blank=True, help_text='Image (URL ou données base64) prise sur site', verbose_name='Photo')),
                ('date_releve', models.DateField(blank=True, null=True, verbose_name='Date du repère')),
                ('ouvrage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='releve_repere', to='cartographie.ouvragehydraulique', verbose_name='Ouvrage')),
            ],
            options={
                'verbose_name': 'Relevé spécialisé — Repère / point intermédiaire',
                'verbose_name_plural': 'Relevés spécialisés — Repères / points intermédiaires',
            },
        ),
    ]
