# Generated by Django 6.0.7 on 2026-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0022_releveconsommation_releverepere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvragehydraulique',
            name='sous_type',
            field=models.CharField(blank=True, choices=[('naturelle', 'Source naturelle'), ('amenagee', 'Source aménagée'), ('forage', 'Forage'), ('puits', 'Puits'), ('riviere', 'Rivière'), ('lac', 'Lac'), ('etang', 'Étang'), ('captage_source', 'Captage'), ('gravitaire', 'Source gravitaire'), ('resurgence', 'Source à résurgence'), ('autre', 'Autre'), ('borne_fontaine', 'Borne-fontaine'), ('robinet_public', 'Robinet public'), ('kiosque_eau', 'Kiosque à eau'), ('point_communautaire', "Point d'eau communautaire"), ('ecole_conso', 'École'), ('centre_sante_conso', 'Centre de santé'), ('institution', 'Institution'), ('autre_desservi', 'Autre point desservi'), ('carrefour', 'Carrefour'), ('route', 'Route'), ('pont', 'Pont'), ('riviere_repere', 'Rivière'), ('ravin', 'Ravin'), ('colline', 'Colline'), ('sommet', 'Sommet'), ('vallee', 'Vallée'), ('ecole_repere', 'École'), ('maison', 'Maison'), ('marche', 'Marché'), ('eglise', 'Église'), ('centre_sante_repere', 'Centre de santé'), ('passage_difficile', 'Passage difficile'), ('zone_rocheuse', 'Zone rocheuse'), ('zone_marecageuse', 'Zone marécageuse'), ('traversee_riviere', 'Traversée de rivière'), ('point_haut', 'Point haut'), ('point_bas', 'Point bas'), ('reservoir_potentiel', 'Emplacement potentiel de réservoir'), ('chambre_vanne_potentielle', 'Emplacement potentiel de chambre de vanne'), ('autre_repere', 'Autre'), ('reservoir', 'Réservoir'), ('chateau_eau', "Château d'eau"), ('station_pompage', 'Station de pompage'), ('chambre_vanne', 'Chambre de vanne'), ('vanne', 'Vanne'), ('ventouse', 'Ventouse'), ('vidange', 'Vidange'), ('traversee_riviere', 'Traversée de rivière'), ('autre_reseau', 'Autre ouvrage du réseau')], default='', help_text="Qualifie le type d'ouvrage (ex : pour source → naturelle, forage, puits…)", max_length=30, verbose_name='Classification / sous-type'),
        ),
        migrations.AlterField(
            model_name='ouvragehydraulique',
            name='type',
            field=models.CharField(choices=[('source', "Source d'eau"), ('captage', 'Captage'), ('borne', 'Borne-fontaine'), ('consommation', 'Point de consommation'), ('reservoir', 'Réservoir'), ('reseau', 'Ouvrage du réseau'), ('ouvrage', 'Ouvrage existant'), ('repere', 'Point de repère'), ('intermediaire', 'Point intermédiaire'), ('village', 'Village desservi')], default='source', max_length=20, verbose_name="Type d'ouvrage"),
        ),
    ]
