# Generated by Django 6.0.7 on 2026-08-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0023_alter_ouvragehydraulique_sous_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveReservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacite_m3', models.FloatField(blank=True, null=True, verbose_name='Capacité (m³)')),
                ('niveau_eau_m', models.FloatField(blank=True, null=True, verbose_name="Niveau d'eau (m)")),
                ('etat', models.CharField(blank=True, choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('hors_service', 'Hors service')], default='', max_length=20, verbose_name='État')),
                ('existant_propose', models.CharField(blank=True, choices=[('existant', 'Existant'), ('propose', 'Proposé')], default='', max_length=10, verbose_name='Existant / proposé')),
                ('photos', models.JSONField(blank=True, default=list, help_text="Liste d'images (URL ou données base64) prises sur site", verbose_name='Photos de terrain')),
                ('ouvrage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='releve_reservoir', to='cartographie.ouvragehydraulique', verbose_name='Ouvrage')),
            ],
            options={
                'verbose_name': "Relevé spécialisé — Réservoir / château d'eau",
                'verbose_name_plural': "Relevés spécialisés — Réservoirs / châteaux d'eau",
            },
        ),
    ]
