# Generated by Django 6.0.7 on 2026-08-08 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0024_relevereservoir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapoint',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='mediapoint',
            name='date_prise',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de la photo'),
        ),
        migrations.AddField(
            model_name='mediapoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='mediapoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='mediapoint',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
