# Generated by Django 6.0.7 on 2026-08-08 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0025_mediapoint_commentaire_mediapoint_date_prise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traceadduction',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces_adduction', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AddField(
            model_name='traceadduction',
            name='synchro_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Identifiant de synchronisation (client)'),
        ),
        migrations.AddField(
            model_name='traceadduction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
