# Generated by Django 6.0.7 on 2026-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0026_traceadduction_synchro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvragehydraulique',
            name='precision_gps_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Précision GPS (m)'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='precision_gps_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Précision GPS (m)'),
        ),
    ]
