# Generated by Django 6.0.7 on 2026-08-15 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0027_qualite_precision_gps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(verbose_name="Debut de l'activite")),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name="Fin de l'activite")),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('activite_nom', models.CharField(blank=True, default='', max_length=255, verbose_name='Activite en cours')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_travail', to='cartographie.projet', verbose_name='Projet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_travail', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session de travail',
                'verbose_name_plural': 'Sessions de travail',
                'ordering': ['-debut'],
            },
        ),
    ]
