# Generated by Django 6.0.7 on 2026-08-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0028_sessiontravail'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='difficultes',
            field=models.TextField(blank=True, default='', verbose_name='Difficultés rencontrées'),
        ),
        migrations.AddField(
            model_name='activite',
            name='enfants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='activite',
            name='femmes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de femmes'),
        ),
        migrations.AddField(
            model_name='activite',
            name='hommes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'hommes"),
        ),
        migrations.AddField(
            model_name='activite',
            name='menages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de ménages concernés'),
        ),
        migrations.AddField(
            model_name='activite',
            name='objectif',
            field=models.TextField(blank=True, default='', verbose_name="Objectif de l'activité"),
        ),
        migrations.AddField(
            model_name='activite',
            name='recommandations',
            field=models.TextField(blank=True, default='', verbose_name='Recommandations'),
        ),
        migrations.AddField(
            model_name='activite',
            name='resultats',
            field=models.TextField(blank=True, default='', verbose_name='Résultats obtenus'),
        ),
        migrations.AddField(
            model_name='projet',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Code / référence du projet'),
        ),
    ]
