# Generated by Django 6.0.7 on 2026-08-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0029_activite_difficultes_activite_enfants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointgeographique',
            name='categorie',
            field=models.CharField(choices=[('hopital', 'Hôpital'), ('ecole', 'École'), ('eglise', 'Église'), ('police', 'Police'), ('marche', 'Marché'), ('projet', 'Projet'), ('incident', 'Incident'), ('village', 'Village'), ('ville', 'Ville'), ('pont', 'Pont'), ('route', 'Route'), ('entreprise', 'Entreprise'), ('zone_rouge', 'Zone rouge'), ('zone_verte', 'Zone verte'), ('zone_orange', 'Zone orange'), ('autre', 'Autre'), ('batiment', 'Bâtiment'), ('centre_sante', 'Centre de santé'), ('poteau', 'Poteau'), ('arbre', 'Arbre'), ('parcelle', 'Parcelle'), ('repere_geodesique', 'Repère géodésique'), ('point_altitude', "Point d'altitude"), ('courbe_niveau', 'Courbe de niveau'), ('zone_leve', 'Zone de levé'), ('station', 'Station topographique'), ('point_gps', 'Point GPS/GNSS'), ('point_topo', 'Point topographique'), ('reseau_eau', 'Ouvrage réseau eau'), ('borne_fontaine', 'Borne-fontaine'), ('reservoir_eau', 'Réservoir d’eau'), ('captage_eau', 'Captage / source')], default='autre', max_length=20, verbose_name='Catégorie'),
        ),
    ]
