# Generated by Django 6.0.7 on 2026-08-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0030_alter_pointgeographique_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude du relevé')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude du relevé')),
                ('localisation', models.CharField(blank=True, default='', max_length=200, verbose_name='Localisation')),
                ('temperature_c', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('conditions', models.CharField(blank=True, default='', max_length=120, verbose_name='Conditions')),
                ('code_conditions', models.IntegerField(blank=True, null=True, verbose_name='Code WMO')),
                ('humidite', models.IntegerField(blank=True, null=True, verbose_name='Humidité (%)')),
                ('vent_kmh', models.FloatField(blank=True, null=True, verbose_name='Vent (km/h)')),
                ('vent_direction', models.CharField(blank=True, default='', max_length=40, verbose_name='Direction du vent')),
                ('vent_direction_deg', models.IntegerField(blank=True, null=True, verbose_name='Direction du vent (°)')),
                ('proba_pluie', models.IntegerField(blank=True, null=True, verbose_name='Probabilité de pluie (%)')),
                ('lever_soleil', models.DateTimeField(blank=True, null=True, verbose_name='Lever du soleil')),
                ('coucher_soleil', models.DateTimeField(blank=True, null=True, verbose_name='Coucher du soleil')),
                ('donnees_disponibles', models.BooleanField(default=False, verbose_name='Données météo disponibles')),
                ('source', models.CharField(choices=[('temps_reel', 'Temps réel'), ('cache', 'Cache local'), ('synchronise', 'Synchronisé')], default='temps_reel', max_length=20, verbose_name='Source')),
                ('horodatage_meteo', models.DateTimeField(blank=True, null=True, verbose_name='Horodatage des données météo')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('activite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meteo', to='cartographie.activite', verbose_name='Activité')),
            ],
            options={
                'verbose_name': "Conditions météo d'activité",
                'verbose_name_plural': 'Conditions météo des activités',
            },
        ),
    ]
