# Generated by Django 6.0.7 on 2026-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0031_meteoactivite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointgeographique',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Date d'encodage"),
        ),
        migrations.AlterField(
            model_name='pointgeographique',
            name='supprime',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Supprimé (corbeille)'),
        ),
        migrations.AlterField(
            model_name='pointgeographique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Dernière modification'),
        ),
    ]
