# Generated by Django 6.0.7 on 2026-08-19 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0032_alter_pointgeographique_date_creation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couchegeometrie',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='encodage',
            field=models.CharField(blank=True, default='UTF-8', max_length=50, verbose_name='Encodage'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='epsg',
            field=models.IntegerField(default=4326, verbose_name='EPSG de la projection source'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='fichier_cpg',
            field=models.FileField(blank=True, upload_to='layers/', verbose_name='Fichier encodage (.cpg)'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='fichier_dbf',
            field=models.FileField(blank=True, upload_to='layers/', verbose_name='Fichier attributs (.dbf)'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='fichier_prj',
            field=models.FileField(blank=True, upload_to='layers/', verbose_name='Fichier projection (.prj)'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='fichier_qmd',
            field=models.FileField(blank=True, upload_to='layers/', verbose_name='Fichier style QGIS (.qmd)'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='fichier_shp',
            field=models.FileField(blank=True, upload_to='layers/', verbose_name='Fichier source (.shp)'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='fichier_shx',
            field=models.FileField(blank=True, upload_to='layers/', verbose_name='Fichier index (.shx)'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='nb_entites',
            field=models.IntegerField(default=0, verbose_name="Nombre d'entités"),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='nom_original',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom original du fichier'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='source',
            field=models.CharField(blank=True, max_length=300, verbose_name='Source / provenance'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée'), ('brouillon', 'Brouillon')], default='active', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='taille_octets',
            field=models.BigIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches_importees', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
