# Generated by Django 6.0.7 on 2026-08-20 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0033_couchegeometrie_date_modification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrie',
            name='categorie',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Catégorie détectée à l'import (propriété du fichier)", max_length=120, verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='SourceGeometrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='Ex. : Source 001 (attribué automatiquement)', max_length=20, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la source')),
                ('couleur', models.CharField(default='#3388ff', max_length=7, verbose_name='Couleur')),
                ('symbole', models.CharField(blank=True, default='', max_length=30, verbose_name='Symbole / icône')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources_geometries', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources_geometries', to='cartographie.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Source de données',
                'verbose_name_plural': 'Sources de données',
                'ordering': ['identifiant'],
            },
        ),
        migrations.AddField(
            model_name='couchegeometrie',
            name='source_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couches', to='cartographie.sourcegeometrie', verbose_name='Source (gestionnaire)'),
        ),
        migrations.AddConstraint(
            model_name='sourcegeometrie',
            constraint=models.UniqueConstraint(fields=('projet', 'identifiant'), name='uniq_source_projet_identifiant'),
        ),
    ]
