# Generated by Django 6.0.7 on 2026-08-20 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0034_geometrie_categorie_sourcegeometrie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointgeographique',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse / localisation'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Agent responsable'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Altitude (m)'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='archive',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Code unique du point dans son projet (ex. P-0001)', max_length=30, verbose_name='Code du point'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='date_visite',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de visite'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='etat_avancement',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name="État d'avancement"),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='identifiant',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Identifiant unique global (issu de l'import ou attribué automatiquement)", max_length=64, verbose_name='Identifiant unique'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='secteur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Secteur / chefferie'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='territoire',
            field=models.CharField(blank=True, max_length=100, verbose_name='Territoire / district'),
        ),
        migrations.AddField(
            model_name='pointgeographique',
            name='village',
            field=models.CharField(blank=True, max_length=100, verbose_name='Village / localité'),
        ),
        migrations.AlterField(
            model_name='pointgeographique',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_crees', to=settings.AUTH_USER_MODEL, verbose_name='Agent créateur'),
        ),
        migrations.AlterField(
            model_name='pointgeographique',
            name='commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='Commune / secteur'),
        ),
        migrations.AlterField(
            model_name='pointgeographique',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('nouveau', 'Nouveau'), ('planifie', 'Planifié'), ('a_visiter', 'À visiter'), ('visite', 'Visité'), ('verifie', 'Vérifié'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='État'),
        ),
        migrations.CreateModel(
            name='HistoriquePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('creation', 'Point créé'), ('modification', 'Information modifiée'), ('coordonnees', 'Coordonnées modifiées'), ('statut', 'Statut modifié'), ('photo', 'Photo ajoutée'), ('document', 'Document ajouté'), ('donnee', 'Donnée enregistrée'), ('activite', 'Activité ajoutée'), ('visite', 'Visite enregistrée'), ('deplacement', 'Point déplacé'), ('archive', 'Point archivé'), ('restauration', 'Point restauré')], default='modification', max_length=20, verbose_name='Type')),
                ('action', models.CharField(max_length=300, verbose_name='Action réalisée')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date et heure')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='cartographie.pointgeographique', verbose_name='Point')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'historique du point",
                'verbose_name_plural': 'Historique des points',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la visite')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / observations')),
                ('resultats', models.TextField(blank=True, verbose_name='Résultats de la visite')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('effectuee', 'Effectuée'), ('partielle', 'Partielle'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_points', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='cartographie.pointgeographique', verbose_name='Point')),
            ],
            options={
                'verbose_name': 'Visite de point',
                'verbose_name_plural': 'Visites de points',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='StatutPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Code du statut')),
                ('nom', models.CharField(max_length=80, verbose_name='Nom affiché')),
                ('couleur', models.CharField(default='#6b729c', max_length=7, verbose_name='Couleur (hex)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuts_points_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('projet', models.ForeignKey(blank=True, help_text='Si défini, le statut est propre au projet ; sinon il est global.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuts_points', to='cartographie.projet', verbose_name='Projet (portée)')),
            ],
            options={
                'verbose_name': 'Statut de point',
                'verbose_name_plural': 'Statuts de points',
                'ordering': ['ordre', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('projet', 'code'), name='uniq_statut_point_projet_code'), models.UniqueConstraint(condition=models.Q(('projet__isnull', True)), fields=('code',), name='uniq_statut_point_global_code')],
            },
        ),
    ]
