# Generated by Django 6.0.7 on 2026-08-20 15:15

from django.db import migrations

STATUTS_PAR_DEFAUT = [
    ('actif', 'Actif', '#16a34a', 10),
    ('nouveau', 'Nouveau', '#2563eb', 20),
    ('planifie', 'Planifié', '#7c3aed', 30),
    ('a_visiter', 'À visiter', '#d97706', 40),
    ('en_cours', 'En cours', '#ea580c', 50),
    ('visite', 'Visité', '#0891b2', 60),
    ('verifie', 'Vérifié', '#059669', 70),
    ('termine', 'Terminé', '#166534', 80),
    ('suspendu', 'Suspendu', '#dc2626', 90),
    ('inactif', 'Inactif', '#64748b', 100),
    ('archive', 'Archivé', '#475569', 110),
]


def semer_statuts(apps, schema_editor):
    StatutPoint = apps.get_model('cartographie', 'StatutPoint')
    for code, nom, couleur, ordre in STATUTS_PAR_DEFAUT:
        StatutPoint.objects.get_or_create(
            projet=None, code=code,
            defaults={'nom': nom, 'couleur': couleur, 'ordre': ordre, 'actif': True},
        )


def backfill_points(apps, schema_editor):
    PointGeographique = apps.get_model('cartographie', 'PointGeographique')
    Projet = apps.get_model('cartographie', 'Projet')
    for point in PointGeographique.objects.filter(code='').iterator():
        prefix = (point.projet.code if point.projet and point.projet.code else 'P').upper().replace(' ', '_')
        point.code = f"{prefix}-{point.pk:04d}"
        if not point.identifiant:
            point.identifiant = point.code
        point.save(update_fields=['code', 'identifiant'])


class Migration(migrations.Migration):

    dependencies = [
        ('cartographie', '0035_pointgeographique_adresse_pointgeographique_agent_and_more'),
    ]

    operations = [
        migrations.RunPython(semer_statuts, migrations.RunPython.noop),
        migrations.RunPython(backfill_points, migrations.RunPython.noop),
    ]